//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservaSala
    {
        public System.Guid Codigo { get; set; }
        public int ID { get; set; }
        public System.DateTime DtInicio { get; set; }
        public System.DateTime DtFim { get; set; }
        public System.Guid UsuarioCodigo { get; set; }
        public System.Guid SalaCodigo { get; set; }
    
        public virtual Sala Sala { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
